<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.1.50</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Authors>AaronoLW</Authors>
    <Copyright>Copyright 2026 AaronoLW</Copyright>
    <RepositoryUrl>https://github.com/Aaron-LW/Smash-Framework</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Description>A very simple framework for making games/graphical applications built on top of SDL3</Description>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="SDL3-CS" Version="3.3.6" />
	  <PackageReference Include="SDL3-CS.Native" Version="3.3.6" />
	  <PackageReference Include="SDL3-CS.Native.Image" Version="3.2.4" />
	  <PackageReference Include="SDL3-CS.Native.TTF" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
   <None Include="..\README.md" Pack="true" PackagePath="\" />
   <None Include="..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
